name: Basic Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running the Github Actions for the first time" 
      - run: echo "<h1> Test </h1>">index.html
      - run: sudo apt-get update 
        
